name: Upload zone files
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate hash files
        run: |
          for tier in {1..6}
          do
            cd "Tier $tier"
            for file in *.zon
            do
              echo -e "Generate hash for $file..."
              sha1sum $file | cut -d " " -f 1 > $file.hash
              mv $file ..
              mv $file.hash..
            done
            cd ..
          done
        working-directory: ./files

      - name: Upload files
        uses: earendildev/backblaze-b2-action@master
        env:
          SOURCE_DIR: './files'
          B2_BUCKET_PATH: ${{ secrets.B2_BUCKET }}
          B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID }}
          B2_APPKEY: ${{ secrets.B2_APPKEY }}
